name: "Pull Request Changelog Generator"
description: "Github action that creates a changelog on opening or updating the PR"
author: "etc-tiago"
branding:
  icon: "git-pull-request"
  color: "green"
inputs:
  token:
    required: true
    description: "As provided by Github Actions"
runs:
  using: "node12"
  main: "dist/index.js"
